title: Get Windows 11
description: Mirrors to download the leaked Windows 11 build.
permalink: /blog/:year/:title/
url: https://gh-phenix.github.io/gw11.tech
logo: /assets/img/favicon.png

socials:
  github: gh-phenixh

compress_html:
  comments: all

exclude:
  - .editorconfig
  - .gitignore
  - .gitattributes
  - .prettierrc
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

markdown: kramdown

kramdown:
  auto_ids: false
  input: GFM

collections:
  - mirrors

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-target-blank

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-target-blank
